// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzSjyPlQgVdU_D3HubROuqrt_nI920dLI',
    appId: '1:236361572090:web:31c8a2bbb3ef6de51f7343',
    messagingSenderId: '236361572090',
    projectId: 'midterm-project-instagram',
    authDomain: 'midterm-project-instagram.firebaseapp.com',
    storageBucket: 'midterm-project-instagram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEv4WNsTwUaFkAXGtgweUkcnWxPzeVa2c',
    appId: '1:236361572090:android:8525e0f64ec0537c1f7343',
    messagingSenderId: '236361572090',
    projectId: 'midterm-project-instagram',
    storageBucket: 'midterm-project-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8p475xkNppVnON-EJOMlIxvJcg4Lvz4U',
    appId: '1:236361572090:ios:c14dc2cc86f8b7ba1f7343',
    messagingSenderId: '236361572090',
    projectId: 'midterm-project-instagram',
    storageBucket: 'midterm-project-instagram.appspot.com',
    iosClientId: '236361572090-drj9qhpfjjmf9umfdg14hqfmvfh9tc1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneApp',
  );
}
